### ISSUE TITLE
Remaining Bugs/Issues for the V2 Development API

### ISSUE THREAD

**Issue by cloneofghosts** [Pirate-Weather/pirateweather#180]
I had wrote this as a comment but for better visibility I'm going to create an issue for it so it doesn't get lost in the other issue.

**Issues**
* #75 - I moved this to the discussions since I feel like it makes more sense there
    * #183 would also be something to look at here (may not be possible for V2 but going to add as a subtask)
* #92 - I think the idea here was to have a AQI value (probably using the US EPA scale) in the API
* #114 
* #32 
* #119 
* #11 

**Nice to have Issues but not critical for V2**
* #154 - I added this one because you said it would be quick to add. Can always remove it from the list if needed
* #152 - Not part of the project but would be a nice addition to V2

**Tasks**
* [x] negative Longitudes displaying incorrectly (-75 shows as 285)
* [x] visibility is not capped
* [x] hourly and daily precipitation data points are rounded to two decimal places instead of four
* [ ] minutely block seems to show array positioning
* [x] Precipitation Probability can go over 1
* [x] UV index can display -0
* [x] `precipIntensity`and `precipAccumulation` can go below zero. (Should check the new ones added as well)
* [x] `nearestStormDistance` and/or `nearestStormBearing` can display -0
* [x] It's possible to not have a precipitation icon/summary when `precipIntensity` is over 0.25mm/h. Might be related to the `precipProbability` change
* [x] The threshold to show the precipitation icon is inconsistent between currently and hourly/daily blocks. Currently shows it no matter the intensity whereas hourly/daily it needs to be above 0.25mm/h. Should be consistent across all blocks
* [x] Daily `precipitationAccumulation` in metric units is wrong unless only snow is forecast.

An example of the precipitation intensity bug I added to the list of tasks:

```
  "currently": {
    "time": 1710893160,
    "summary": "Cloudy",
    "icon": "cloudy",
    "nearestStormDistance": 35.47,
    "nearestStormBearing": 63,
    "precipIntensity": 0.5602,
    "precipProbability": 0.16,
    "precipIntensityError": 0.14,
    "precipType": "snow",
    "temperature": -0.15,
    "apparentTemperature": -4.02,
    "dewPoint": -0.71,
    "humidity": 0.79,
    "pressure": 989.92,
    "windSpeed": 12.88,
    "windGust": 26.87,
    "windBearing": 184,
    "cloudCover": 0.92,
    "uvIndex": 0,
    "visibility": 6.51,
    "ozone": 413.48
  },
```

Examples of negative `precipAccumulation` and `precipInsensity`:

<details>
	<summary>Hourly</summary>

```
      {
        "time": 1711015200,
        "icon": "wind",
        "summary": "Windy",
        "precipIntensity": -0.21,
        "precipProbability": 0.06,
        "precipIntensityError": 0.04,
        "precipAccumulation": -0.2,
        "precipType": "snow",
      },
```

</details>

<details>
	<summary>Daily</summary>

```
      {
        "time": 1710993600,
        "icon": "partly-cloudy-day",
        "summary": "Partly Cloudy",
        "sunriseTime": 1711018996,
        "sunsetTime": 1711063029,
        "moonPhase": 0.42,
        "precipIntensity": -0.04,
        "precipIntensityMax": 0.25,
        "precipIntensityMaxTime": 1710993600,
        "precipProbability": 0.18,
        "precipAccumulation": -0.8999999999999999,
        "precipType": "snow",
      },
```

</details>

On Wednesday the API is predicting rain and snow and using the V2 flag it shows this for the liquid/snow accumulation:

```
"liquidAccumulation": 1.8,
"snowAccumulation": 11.4,
"iceAccumulation": 0
```

I would expect the `precipAccumulation` to be 11.58 but instead it shows `"precipAccumulation": 2.94,`. It seems like it's converting the `snowAccumulation` to cm instead of the `liquidAccumulation` like I would expect. It's only converting the `snowAccumulation` when there is mixed precipitation otherwise it just shows the value of `snowAccumulation`. Rain is also not being converted into cm as it is also just using the value of `liquidAccumulation`.

**Comment by cloneofghosts** [comment]
This issue is meant to be locked so it doesn't get lost in the other issue. Any issues should be reported in #155

**Comment by alexander0042** [comment]
Sorry, didn't mean to re-open this!

**Comment by cloneofghosts** [comment]
This is separate from the original list I created. I figured making it it's own issue would help so it doesn't get lost in the other bugs issue since it'll be pretty active with other people reporting bugs. I re-opened but I can close it if you'd like.
